# Generated by Django 5.2.9 on 2026-01-26 04:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('min_order_amount_for_free_delivery', models.DecimalField(decimal_places=2, default=2000, help_text='При заказе дороже этой суммы доставка бесплатная', max_digits=10, verbose_name='Минимальная сумма для бесплатной доставки')),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=200, help_text='Стоимость обычной доставки при заказе дешевле мин. суммы', max_digits=10, verbose_name='Стоимость доставки')),
                ('express_delivery_cost', models.DecimalField(decimal_places=2, default=500, help_text='Фиксированная стоимость экспресс-доставки', max_digits=10, verbose_name='Стоимость экспресс-доставки')),
            ],
            options={
                'verbose_name': 'Настройки доставки',
                'verbose_name_plural': 'Настройки доставки',
            },
        ),
        migrations.CreateModel(
            name='DeliveryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_express', models.BooleanField(default=False, help_text='Отметьте, если это тип экспресс-доставки', verbose_name='Экспресс-доставка')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Тип доставки',
                'verbose_name_plural': 'Типы доставки',
            },
        ),
        migrations.CreateModel(
            name='TradePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('delivery_policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trade_points', to='market.deliverysettings')),
                ('possible_delivery_type', models.ManyToManyField(blank=True, related_name='trade_points', to='market.deliverytype', verbose_name='Возможные типы доставки')),
            ],
            options={
                'verbose_name': 'Торговая точка',
                'verbose_name_plural': 'Торговые точки',
            },
        ),
    ]
