# Generated by Django 5.2.9 on 2026-01-07 06:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(regex='^\\+?7?\\d{10,11}$')], verbose_name='Телефон')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='BankCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Введите номер карты в формате XXXX XXXX XXXX XXXX', max_length=19, verbose_name='Номер карты')),
                ('expiry_date', models.CharField(help_text='Формат: MM/YY', max_length=5, verbose_name='Срок действия')),
                ('cvv', models.CharField(help_text='3-х значный код на обороте карты', max_length=3, verbose_name='CVV')),
                ('cardholder_name', models.CharField(max_length=100, verbose_name='Имя держателя карты')),
                ('is_default', models.BooleanField(default=False, help_text='Использовать по умолчанию для оплаты', verbose_name='Основная карта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_carts', to='accounts.profile', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Банковская карта',
                'verbose_name_plural': 'Банковские карты',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
